export enum ErrorCode {
    INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
    TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
    INVALID_AMOUNT = 'INVALID_AMOUNT',
    REFUND_AMOUNT_EXCEEDS_PURCHASE_AMOUNT = 'REFUND_AMOUNT_EXCEEDS_PURCHASE_AMOUNT',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}